### ISSUE TITLE
Generalization

### ISSUE THREAD

**Issue by CarterGrove24** [Collegeville/e4s-info#9]
Need to change the command to a more generalized command. This will be done in the following ways: 
- Generalize the command name to `e4s-info`
- The new command should print out information on why, what, who, where, or how information about E4S
- This command will have an option to have an argument that decides what type of information the user wants
   - e.g.: `e4s-info -why`
- These changes should be reflected in `man e4s-info` and `e4s-info --help`

**Comment by CarterGrove24** [comment]
This generalization will likely have side effects:
- Change in file structure
- Loss of index choice

**Comment by maherou** [comment]
@CarterGrove24: I think we want the following structure:

```e4s-info why```

No dash in front of the why.

I don't think that this change will require a loss in index choice.  In fact, I think you can and should still have separate files for each option of who, what, where, why, and when

**Comment by CarterGrove24** [comment]
The "Generalization" (96b3774) commit changed the command, options, associated files to be more generalized. The ability to specify an index is still available.
